---
name: build
on:
    push: ~
    pull_request: ~

jobs:
    phpunit:
        name: Tests on ${{ matrix.php }} ${{ matrix.composer-flags }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ '7.4' , '8.0']
                composer-flags: [ '' ]
        steps:
            - uses: actions/checkout@v2
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: pcov
                  tools: composer:v2, phpspec
            - run: composer update --no-progress ${{ matrix.composer-flags }}
            - run: vendor/bin/phpspec run
            - run: composer psalm
              if: ${{ matrix.php == '8.0' }}
            - run: composer phpstan
              if: ${{ matrix.php == '8.0' }}
            - run: composer phpcs
              if: ${{ matrix.php == '8.0' }}
